[package]
name = "terrain-generation"
version = "0.1.0"
authors = ["Arnaud Valensi <arnaud.valensi@gmail.com>"]
edition = "2018"

[dependencies]
gfx = "0.17.1"
gfx_window_glutin = "0.26.0"
gfx_device_gl = "*"
glutin = "0.18.0"
